spring:
  application:
    name: fisioapp

  datasource:
    url: jdbc:mysql://localhost:3306/fisioapp
    username: root
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  mail:
    host: ${SMTP_MAIL_SERVER}
    port: ${SMTP_MAIL_PORT}
    username: ${SMTP_MAIL_ACCOUNT}
    password: ${SMTP_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enabled: true
